### ISSUE TITLE
Timer for verification does not stop

### ISSUE THREAD

**Issue by Objections** [CAAL/CAAL#109]
If you create a problem where it can not verify and then click twice on the run button it will not stop counting and seemingly it will not stop computing until you close the tab. If you click the run button again it will start over but it still will not end.

**Comment by FuzzyAzurik** [comment]
To reproduce the problem:
select program Orchard,
goto verifier, 
add strong distinguishing formula,
select the processes Spec and Orchard,
and double click the play button.
