### ISSUE TITLE
Verifier TopFormula box crashes

### ISSUE THREAD

**Issue by Reedtz** [CAAL/CAAL#112]
The box reaches the limit, the entire website freezes and you are unable to do anything. Does the same in Internet Explorer

**Comment by FuzzyAzurik** [comment]
The verifier also crashes when pressing enter(Linux and Win Chrome) (trying to make a new line) in top formula box.

Although Jiri(chrome Mac OS) was able to create a newline in the top fomula

**Comment by senevoldsen90** [comment]
This also happens in FF on Windows. And also when making a long line.

**Comment by FuzzyAzurik** [comment]
This is no longer the case in the new verifier design, but it is possible to create multiple lines now.
