### ISSUE TITLE
Wrong Level Calculation in Local Smolka algorithm

### ISSUE THREAD

**Issue by senevoldsen90** [CAAL/CAAL#115]
The level assigned to a source node for a hyperedge should never be lower than the target.

**Comment by FuzzyAzurik** [comment]
Use this test senario, to verify correct level assignment(HML game):
Program:
Man = 'shake.(redapple.walk.Man + greenapple.walk.Man);
AppleTree = shake.('greenapple.AppleTree + 'redapple.AppleTree + break.0);
Orchard = (AppleTree | Man) \ {shake, redapple, greenapple};
Spec = walk.Spec;
HML formula: (satisfied, the defender(AI), should win)
Process: Orchard
Top: X;
Definition: X min= <->X or [[walk]]F;

Defender should force the attacker to walk from the deadlock, which of cause the attacker is not able to do, and thereby loses.
