### ISSUE TITLE
Add TCCS Syntax in help menu

### ISSUE THREAD

**Issue by poohzrn** [CAAL/CAAL#121]
When looking through the help menu examples of TCCS syntax is missing. --- (delay/epsilon syntax)
Maybe add `help-dialog-body-par2` around [the other help-dialog-body-pars](https://github.com/CAAL/CAAL/blob/b9b1a728f2a8c9ed70b6385bb2c060ddb3f4ab9f/index.html#L447#L537)

**Comment by FuzzyAzurik** [comment]
Help menu:
  Add timed - double table line, add delay prefixing
  Add thml paragraph
