### ISSUE TITLE
weak/strong Trace Inlcusion reworked

### ISSUE THREAD

**Issue by FuzzyAzurik** [CAAL/CAAL#127]
weak/strong Trace incluison should be reworked so it works in a similar fashion as strong/weak bisimulation and generating a distinguishing formula.
When trace has been found it should simply add two HML properties with the HML formula, like distinguishing formula for bisimulation.

**Comment by senevoldsen90** [comment]
Currently inclusion does work like that. Do you mean trace equivalence?

**Comment by FuzzyAzurik** [comment]
When two processes are trace included nothing should happen other that a green check mark appear.

if two processes are not trace included, a hml property should appear for each process, and display the  distinguishing trace.
