### ISSUE TITLE
Strict path bug when full from process appears twice in path.

### ISSUE THREAD

**Issue by senevoldsen90** [CAAL/CAAL#139]
This process  `P = tau.a.tau.P;`  has a wrong strict path   `P --a-> 1`  , where `1 = a.tau.P;`. The correct answer should be `P --tau--> 1 --a--> 2 -tau--> P --tau --> 1`.

The errorneous output is partly caused by P appearing early in the path.

**Comment by BannedNexus** [comment]
Also try:
`P = tau.a.tau.Q;`
`Q = P;`
This is the same process, but it will show the correct answer.
