### ISSUE TITLE
Explorer expand performance bug

### ISSUE THREAD

**Issue by senevoldsen90** [CAAL/CAAL#18]
The graph becomes unresponsive to clicks when the graph gets larger. The "logic" expansion of the graph is quite fast, max 30ms for total expansion of ABP. However, expanding with a depth if say 3 it quickly begans taking 1 or 2 seconds to respond.

Believe it has something to do with Arbor.js or our rendering.

**Comment by FuzzyAzurik** [comment]
This might be resolved when changing from using arbor to d3 #58

**Comment by senevoldsen90** [comment]
When switching away from the explorer, it should not spend processing power rearranging the now hidden graph.

**Comment by FuzzyAzurik** [comment]
Solution: freeze the graph when switching activity, there should be a onHide in the explorer activity.

**Comment by senevoldsen90** [comment]
I've added the freeze to the explorer, but Arbor doesn't freeze immediately  https://github.com/samizdatco/arbor/issues/21  although it does seem to take shorter amount of time. Something similar should perhaps be done for the games.

**Comment by FuzzyAzurik** [comment]
I have a created a issue #135 for freezing the arbor graph when switching activity.

**Comment by senevoldsen90** [comment]
This seems to be dependent on which browser is used. Chrome handles the explorer better, but is slightly slower than FF at verification. Closed.
