### ISSUE TITLE
The graph layout should be saved

### ISSUE THREAD

**Issue by FuzzyAzurik** [CAAL/CAAL#47]
When saving a project the current/explored graph's layout(meaning the position of the nodes, and freeze state) should be saved together with the program source-code. And of course there should also be support for load the graph again.

**Comment by FuzzyAzurik** [comment]
Is this really a good idea?
Even so, i believe it has a low priority

**Comment by senevoldsen90** [comment]
This feature is deemed to have too low value for the effort involved.
