### ISSUE TITLE
Show trace(discuss)

### ISSUE THREAD

**Issue by FuzzyAzurik** [CAAL/CAAL#55]
Be able to show trace for a given verification property, so after checking a property(lets say strong bisimulation on two processes) if it fails(or succeds?) the user should be able to press "Show trace" (discuss how this should be implemented)

**Comment by senevoldsen90** [comment]
For non-bisimilar processes there is distinguishing formula now. For non-trace-equivalence (inclusion) a formula of the form <a><b><c>tt or ff is generated. Should this be closed?
