### ISSUE TITLE
Bisimulation Collapse

### ISSUE THREAD

**Issue by FuzzyAzurik** [CAAL/CAAL#60]
Collapse bisimilar states, to remove the tau transitions that are not necessary. 
Use global algorithm.

Jiri's notes:
[S] = { t | s ~ t }
if there exists a t in [S] s.t. t -a-> t' then [S] -a-> [t']

**Comment by senevoldsen90** [comment]
This is partially completed. The collapse should work fine. The dependency graph needs to contain all process pairs in order to collapse all... Also currently the reducer runs before the collapse thus the resulting tau self loops are not removed.

**Comment by senevoldsen90** [comment]
Almost working now. There is an inconsistency that remains:

strong collapse, weak transition. Using weak transition instead of strong transitions increases the total number of states.

P = a. Q + a.P + a.T;
Q = b.P;
T = b.P;

**Comment by senevoldsen90** [comment]
Also the transition table source definitions properly map named processes to their names, whereas the tooltip for the graph shows the id instead.

**Comment by senevoldsen90** [comment]
The tooltip for the graph is now fixed.
