### ISSUE TITLE
Level on DG.

### ISSUE THREAD

**Issue by figa12** [CAAL/CAAL#79]
The dependency graph should have level. Without levels the attacker can be stuck in a loop, which should not happen.

**Comment by FuzzyAzurik** [comment]
This seems to hard to implement, talk to jiri about this on wednesday d. 18.02.2015

**Comment by FuzzyAzurik** [comment]
Is this implemented? can it be closed?

**Comment by senevoldsen90** [comment]
Yes I believe so. Although only for global algorithm, but see no need for it in the local at the moment.
