### ISSUE TITLE
Node follows cursor

### ISSUE THREAD

**Issue by FuzzyAzurik** [CAAL/CAAL#82]
Develop branch: Now that explorer has been resdesigned there sometimes occur a bug when trying to expand a node. when clicking it keeps following the cursor. I suspect that it has something to do with the event handlers.

**Comment by FuzzyAzurik** [comment]
I have a really hard time recreating this bug(actually i have not yet been able to recreate it). Jesper mentioned that there is a console error when the bug happens. it would be nice to know what it says.

**Comment by matmunk** [comment]
Explorer.ts 261 : Uncaught #<Object>

**Comment by FuzzyAzurik** [comment]
For some reasen the graph gets reset when switching between editor and explorer(this only happens for the peterson algorithm???)

**Comment by FuzzyAzurik** [comment]
Error was found, when switching between editor and explorer, the checkprecondition in explorer would re-set the graph. and so when explorering the peterson algorithm, which node mainly consist of auto-generated nodes, it would not work since the user would be trying to explore a node that has not yet known to the graph.
