### ISSUE TITLE
Explorer doesn't load anything. It is empty.

### ISSUE THREAD

**Issue by figa12** [CAAL/CAAL#88]
This sometimes happen, but I do not know how to recreate it. It seems random (it's obviously not of course).

**Comment by FuzzyAzurik** [comment]
This seems to be  reoccurring bug, it  have to be investigated...

**Comment by FuzzyAzurik** [comment]
Does this happen anymore? It has been a while since i have seen this bug occur.

**Comment by figa12** [comment]
I haven't seen this occur in a couple of months either.
